//public class TheQuery {
//    {"count":2,
//    "start":0,
//    "limit":10,
//        "docs":[
//            {"ingestType":"item",
//                "ingestionSequence":999999,
//                "ingestDate":"2016-06-17",
//                "@context":"http://dp.la/api/items/context",
//                "aggregatedCHO":"#sourceResource",
//                "@id":"http://dp.la/api/items/2637f86c593e33c6d4cdf060438c3cad",
//                "id":"2637f86c593e33c6d4cdf060438c3cad",
//                "dataProvider":"San Diego History Center (formerly San Diego Historical Society)",
//                "originalRecord":"http://ldp.dp.la/ldp/original_record/2637f86c593e33c6d4cdf060438c3cad.json",
//                "sourceResource":{"@id":"http://dp.la/api/items/2637f86c593e33c6d4cdf060438c3cad#sourceResource",
//                    "creator":["Unknown]"],
//                    "format":["1 negative : film, b\u0026w, 4 x 5 in. JPEG"],
//                    "identifier":["http://ark.cdlib.org/ark:/13030/kt2n39q13v","84_15225-49 CD M0196 (4076-2121-3475) 84_15225-49 ark:/13030/kt2n39q13v"],
//                    "language":[{"name":"English"}],
//                    "publisher":["San Diego Historical Society"],
//                    "rights":"All San Diego Historical Society photographs are protected by international copyright and are the exclusive property of the San Diego Historical Society. http://www.sandiegohistory.org/orderjoin/copyright.htm",
//                    "title":["Frank Woodford(?), Frank Stephens and Frank Halzner with dead squirrels outside a cabin"],
//                    "collection":[{"title":["California Border Region Digitization Project"],"@id":"_:15554ce0c09135","id":"_:15554ce0c09135"}],
//                    "type":"image","spatial":[{"name":"San Diego County (Calif.)"}],
//                "subject":[{"name":"People Groups Scientists; Cabins; Dead animals; Squirrels"}]},
//                "provider":{"name":"California Digital Library","@id":"http://dp.la/api/contributor/cdl"},
//                "isShownAt":"http://ark.cdlib.org/ark:/13030/kt2n39q13v",
//                "object":"https://thumbnails.calisphere.org/clip/150x150/38c61c5a3cd855b10c71ea0a3b32d915",
//                "_id":"2637f86c593e33c6d4cdf060438c3cad",
//            "score":3.37111},
//            {"@context":"http://dp.la/api/items/context",
//                "isShownAt":"http://digitallibrary.usc.edu/cdm/ref/collection/p15799coll65/id/9310",
//                "dataProvider":"California Historical Society",
//                "@type":"ore:Aggregation",
//                "provider":{"@id":"http://dp.la/api/contributor/usc","name":"University of Southern California. Libraries"},
//                "object":"http://digitallibrary.usc.edu/utils/getthumbnail/collection/p15799coll65/id/9310",
//                "ingestionSequence":20,
//                "ingestDate":"2016-07-04T00:32:46.590150Z",
//                "_rev":"3-60c6a917bdc71cf449baa04dff3b174e",
//                "id":"0a16a29038a3866a6d3663a1a03f1bb2",
//                "aggregatedCHO":"#sourceResource",
//                "_id":"usc--http://digitallibrary.usc.edu/cdm/ref/collection/p15799coll65/id/9310",
//                "admin":{"validation_message":null,
//                "object_status":1,
//                "sourceResource":{"title":"Viele store, stage station, hotel, and post office at Pala, California, ca.1901-1905"},
//                "valid_after_enrich":true},
//                "sourceResource":{"title":"Viele store, stage station, hotel, and post office at Pala, California, ca.1901-1905","spatial":[{"name":"Pala"},{"county":"San Diego","name":"San Diego","state":"California","coordinates":"32.71533, -117.15726","country":"United States"},{"name":"USA"}],"description":"Photograph of the Viele general store, stage station, hotel, and post office at Pala, California, ca.1901-1905 (ca.1920?). Two men relax under the wooden porch roof of the one-story building. A dog stands near one of the men. Boxes, barrels, and other supplies sit nearby. Legible writing includes: \"Kill squirrels and gophers now, Wakelee's [...] never fails, [...], effective, economical\", \"Adriance Buckeye mowers\", ...\"Royal Sayon\".","subject":[{"name":"Butterfield Stage"},{"name":"Pala Indians"},{"name":"Assistencia of San Antonio at Pala Mission"},{"name":"Transportation features"},{"name":"San Diego County--Architecture--Adobes"},{"name":"Transportation--Draft--Stage coaches--Stations"},{"name":"Indians--Mission--Pala"},{"name":"Coaching"},{"name":"Postal service"},{"name":"Hotels, taverns, etc"},{"name":"Horses"},{"name":"Terminals (Transportation)"},{"name":"Adobe brick"}],"rights":["Public Domain. Release under the CC BY Attribution license--http://creativecommons.org/licenses/by/3.0/--Credit both \u201cUniversity of Southern California. Libraries\u201d and \u201cCalifornia Historical Society\u201d as the source. Digitally reproduced by the USC Digital Library; From the California Historical Society Collection at the University of Southern California","Send requests to address or e-mail given. Phone (213) 740-5900; fax (213) 740-2343","USC Libraries Special Collections","Doheny Memorial Library, Los Angeles, CA 90089-0189","Specol@usc.edu"],"relation":["Chs-m265","California Historical Society Collection, 1860-1960","Title Insurance and Trust, and C.C. Pierce Photography Collection, 1860-1960","USC"],"format":["Glass plate negatives","3 photographs : glass photonegative, photoprints, b 17 x 22 cm.","Photographic prints","Photographs"],"@id":"http://dp.la/api/items/0a16a29038a3866a6d3663a1a03f1bb2#sourceResource","date":{"displayDate":"1900","end":"1900","begin":"1900"},"type":"image","publisher":"University of Southern California. Libraries"},
//                "@id":"http://dp.la/api/items/0a16a29038a3866a6d3663a1a03f1bb2",
//                    "ingestType":"item",
//                    "originalRecord":{"handle":["chs-m8951; USC-1-1-1-9088; USC-1-1-1-11995; USC-1-1-1-13925; USC-1-1-1-14077","CHS-3989","http://digitallibrary.usc.edu/cdm/ref/collection/p15799coll65/id/9310"],"status":[],"setSpec":"p15799coll65","subject":["Butterfield Stage; Pala Indians; Assistencia of San Antonio at Pala Mission","transportation features","San Diego County -- Architecture -- Adobes; Transportation -- Draft -- Stage coaches -- Stations; Indians -- Mission -- Pala","Coaching; Postal service; Hotels, taverns, etc.; Horses; Terminals (Transportation); Adobe brick"],"relation":["chs-m265","California Historical Society Collection, 1860-1960","Title Insurance and Trust, and C.C. Pierce Photography Collection, 1860-1960","USC"],"rights":["Public Domain. Release under the CC BY Attribution license -- http://creativecommons.org/licenses/by/3.0/ -- Credit both \u201cUniversity of Southern California. Libraries\u201d and \u201cCalifornia Historical Society\u201d as the source. Digitally reproduced by the USC Digital Library; From the California Historical Society Collection at the University of Southern California","Send requests to address or e-mail given. Phone (213) 740-5900; fax (213) 740-2343","USC Libraries Special Collections","Doheny Memorial Library, Los Angeles, CA 90089-0189","specol@usc.edu"],"label":"Viele store, stage station, hotel, and post office at Pala, California, ca.1901-1905","provider":{"@id":"http://dp.la/api/contributor/usc","name":"University of Southern California. Libraries"},"collection":{"id":"11a0ebbc293994da789948d5a5c380ca","description":"chs","title":"California Historical Society Collection, 1860-1960","@id":"http://dp.la/api/collections/11a0ebbc293994da789948d5a5c380ca"},"format":["glass plate negatives","3 photographs : glass photonegative, photoprints, b 17 x 22 cm.","photographic prints; photographs"],"type":["images","item"],"date":["circa 1901/1905","1900; 1901; 1902; 1903; 1904; 1905; 1906","2000"],"publisher":"University of Southern California. Libraries","id":"oai:digitallibrary.usc.edu:p15799coll65/9310","title":"Viele store, stage station, hotel, and post office at Pala, California, ca.1901-1905","source":["California Historical Society","3989","CHS-3989","1-33-; 1-155-"],"coverage":["Pala","San Diego","California","USA","circa 1901/1905","1900; 1901; 1902; 1903; 1904; 1905; 1906"],"description":"Photograph of the Viele general store, stage station, hotel, and post office at Pala, California, ca.1901-1905 (ca.1920?). Two men relax under the wooden porch roof of the one-story building. A dog stands near one of the men. Boxes, barrels, and other supplies sit nearby. Legible writing includes: \"Kill squirrels and gophers now, Wakelee's [...] never fails, [...], effective, economical\", \"Adriance Buckeye mowers\", ...\"Royal Sayon\".","datestamp":"2013-11-05"},
//            "score":0.6149167}
//        ]
//    ,"facets":[]}
//}
